### ISSUE TITLE
Turn off ALL notifications 

### ISSUE THREAD

**Issue by Theletha** [funkydude/BugSack#10]
something that really grinds my gear is that it keeps spamming me with messages in the chat that im getting errors from addons like its really going at it i can't even see messages in the chat cause it spamming so much. the addons that are giving me error is working for what i need them to and the game performance is not impacted.  it would be great if you could mute all notifications or make it only send out 1 message per session (not including UI reload).
i don't know if there is a option like this already i have only found the mute audio option...
please add a darn mute all messages option!

**Comment by funkydude** [comment]
A few things here:
1. Chat frame prints are off by default, you've purposely turned them on in the config. Simple solution, turn them off.
2. There's a mute option for the audio.
3. Stating that an addon that keeps erroring "is working" is moronic. If it is erroring, it is not working.

Closing.

**Comment by Theletha** [comment]
but it still is pumping out messages.. 

https://i.imgur.com/0Ni5d8W.png

can you make an option to  turn these off?

**Comment by funkydude** [comment]
The only moronic thing here is you reporting issues with other addons to me instead of to the author.

The throttle is designed to kick in when a massive amount of errors are detected, it pauses error capture for 10 seconds. The addon at fault is probably erroring inside a rapidly repeating timer, which WILL cause performance issues. Stop wasting my time and go complain to the addon author.
