### ISSUE TITLE
Classic Cataclysm does not work with BugGrabber anymore

### ISSUE THREAD

**Issue by Amd321** [funkydude/BugSack#103]
(Sorry, tagged for Classic because no Cataclysm tag exists in selection)

## Describe the problem
For Classic Cataclysm, BugSack does not work anymore with BugGrabber, because BugGrabber is not recognized. Version !BugGrabber-v10.2.5 is no longer recognized as an addon by Classic Cataclysm, which prevents BugSack from being able to perform its functions. When installed, BugSack tells you it requires BugGrabber to function. Reverting to BugGrabber-v10.2.4 causes functionality to be restored.

### What steps will reproduce the problem?

1.  Update to latest live version of BugSack (BugSack-v10.2.6)
2.  Update to latest live version of BugGrabber (!BugGrabber-v10.2.5)
3.  BugGrabber is not recognized

**Comment by funkydude** [comment]
You updated with the game open, restart the game. If that doesn't work, restart your PC.

**Comment by Amd321** [comment]
I did not. I updated it with the game not even active. It does not work. It's not working for several other people I know as well. Nice response though. Uninstalled. Will be warning everyone I know to use a different addon.

**Comment by funkydude** [comment]
The reason this happened is because the `toc` architecture for the addon changed. This is a breaking change only for classic users, which you have stated you are.
I made this change to BugSack itself [last month](https://github.com/funkydude/BugSack/commit/b8f76e0238307eac67300c2d2c8449499519ccf2) and had the exact same complaints from classic users. In every case, restarting the game or their PC fixed it for them.
Now the change was made to BuggGrabber the same complaints are here again, but with that addon. Hence that's the most likely explanation.

If that doesn't work for you, you can try uninstalling and reinstalling. I have no other suggestions for you.
But since you already uninstalled, you don't know to.
You and "several other people" know better after all. You're the special few amongst the over 200k users that have no issues.
Cya!
