### ISSUE TITLE
Alt-click to clear bugs

### ISSUE THREAD

**Issue by WoLf-** [funkydude/BugSack#46]
The ability to alt-click the BugSack icon to clear recorded bugs is important for development..
It always been possible to quickly check the stack at a glance while testing changes, alt-click to clear, replicate one issue in interface, single line pops up in tooltip, shift-click to reload, without having to open the options or the main window.

Please consider [**making it an option**] for who actually used it, at least.. Or [**move the wipe button to the main interface instead of settings**].
Thanks

**Comment by GregoryGH** [comment]
Very annoying to not have this feature. Had to revert to previous version.

**Comment by Nillx** [comment]
Why was this removed? You need to open the addon settings now and clear the bugs like that.

**Comment by chrisd08** [comment]
W-w-why would you remove that?

**Comment by acabtr** [comment]
Big downgrade in functionality, please add it back as an option at least.

**Comment by Tga123** [comment]
If you worried about that reasone: 
**_"For reasons unknown, some people habitually click this right after an error occurs to the point they are "automatically" doing it even when they actually need the error to provide to an author. "_**
you can make two versions for developers and for regular users.
Alt+click clearing is very useful and important feature that seriously simplified addons debugging.

**Comment by CruelDrool** [comment]
> Big downgrade in functionality, please add it back as an option at least.

I second this suggestion. Really miss the quick clear of the bug sack.

**Comment by k1ck3r** [comment]
until author decides our requests for returning of ALT+click, here you can find what's exactly is missing in `ldb.lua` here: https://github.com/funkydude/BugSack/commit/0d9c02830c4308ffda0df880724b89b510afe3ed

**Comment by funkydude** [comment]
I left this open because I'm interested in hearing people's suggestions.
2 examples of good feedback would be:

"I've read and understood why this change was made but I disagree with this change and my reason is [insert reason]"
or
"My suggestion for an alternative implementation is [insert suggestion]

You can use the thumbs up on which you think is the best suggestion and that is most likely what will happen.
To keep the discussion focused, comments that don't add anything will be deleted.

**Comment by k1ck3r** [comment]
To be honest, i'm using a broker (not the minimap button) and i know when i want to see the error.
Also using the 'hovering' option allows you to read the first line of the error, and if it's know, alt+clicking is hugely missed. 

However, i understand why you did this, but instead of completely removing the ability to easy clear the errors you could just implement different combination and announce it upon releasing.

accept my apologies if i was the user who actually triggered your actions - didn't meant that at all.

**Comment by WoLf-** [comment]
Thank you for considering this. I'll expand on my reason for raising this issue.
I do understand what made you remove the functionality from the addon, but would disagree on the outcome.

The fact that some users might misuse it without understanding would be easier to correct by telling them to reload ui to collect the bug, when and if this issues happens while receiving a bug report. (most people already directly paste the bug, or don't know how to so we have to explain anyway)

For everyone else, it's a missing feature that we got used to in our workflow. Clearing the stack also allows you to quickly see what actions triggers a bug, instead of having to check the repetitions number on each bug entry.

Personally I'd think a solution that would help both sides is to **[have alt-click as an option]**, as I had mentioned originally. Default to off so that would keep it disabled for the "just click through without reading" problematic users, without punishing everyone else for it.

**Comment by GregoryGH** [comment]
If ppl dont bother to report errors you wont make them do that if you remove alt-click. But you annoy ppl who do report errors as well. Does it worth it to annoy good ppl because of bad? Dont think so.

**Comment by syndenbock** [comment]
I agree that while the reason for this change is understandable, the underlying "problem" is just people having developed a bad habit as it's very unlikely they hold the alt-key by accident. And in my opininion removing a pretty essential shortcut for debugging is too big of a drawback in exchange for fixing a bad habit.
Therefor I'm all for adding alt-clicking to clear errors back in alongside an option to disable the function.

**Comment by SiderealDay** [comment]
Please consider adding alt-click back. Removing it will not incentivize players to report properly.
Or as already suggested. you can always make it a togglable option.
Eitherway, thank you for this addon :)

**Comment by GurliGebis** [comment]
Please add it back as an option that can be enabled, and keep it disabled as default.
For developing, it speeds things up being able to clear the list and refresh.

**Comment by Altoholic** [comment]
Even as a code illiterate person, alt-clicking was very useful : when an error occur, i read it first, and consider if i can make a bug report of it, but the next 20 times it happen (i play with 20 characters), i just alt-click it.

**Comment by Toludin** [comment]
I'd just like to all state that it would be great to see this come back as an default-off option within the settings, which should both offer protection for those who don't want this feature (or are unaware of it) but still allow those who rely on it for development or just quality of life to opt in. Thanks!

**Comment by Intervencion** [comment]
I second my peers, some of the addons I use in Classic are old and/or abandoned so reporting the bug isn't really useful (specially if it's just some locale problem that doesn't really affect anything).

Have the option to clear bugs disabled on default and a toggle in settings to enable it back would be what I would do, personally ^^

**Comment by niketa-wow** [comment]
I want to add this here, hopefully not to have this turned into a private function (cause anyone who decides to use this macro knows what they are doing and are not the people this feature was removed because), but to help out anyone during development in the meantime. 

I just use this macro:

`/run BugSack:Reset()`

It might not be as convenient as the broker alt click, but at least it'll let you clear the bugs for now.

**Comment by ijoihlhnn** [comment]
Thanks for adding it back! i mainly used it AFTER i reported the error to the Addon Author and in the meantime it gets worked on just deleted the error.

**Comment by funkydude** [comment]
It's obvious nothing new in terms of actual suggestions is going to be added to this thread so I'm locking it here. It won't be closed until a toggle is implemented.
