### ISSUE TITLE
Make BugGrabber available through GitHub

### ISSUE THREAD

**Issue by pingje** [funkydude/BugSack#56]
Please consider making BugGrabber available on GitHub, so that it and BugSack can be installed without relying on Curse.

**Comment by funkydude** [comment]
Unlikely to ever happen due to BugGrabber being an embed in multiple addons.

Also I like how many "anti Curse" people are also never subscribed to any addon authors. https://github.com/sponsors/funkydude?frequency=recurring

You can always download manually.

**Comment by pingje** [comment]
Especially around patch days, Curse's infrastructure tends to be pretty unreliable, which is why I asked. I'd been unaware of your GitHub presence until recently, and it seemed odd to have only one half of the pair (BugGrabber and BugSack) available on here. 
I'm not anti-Curse. I support many add-on authors through Patreon. In this case when I tried to sponsor you, GitHub didn't like my card details for some reason and in theory is going to retry sometime within two weeks. (There are a few days left in that period.)

**Comment by funkydude** [comment]
Alright, thank you.

Yes it may seem strange but BugSack is its own dedicated addon where as BugGrabber is a hybrid addon and library. None of my libraries can be moved to GitHub because it would break the addons depending on them (pointing to the CurseForge repos) and the same applies to BugGrabber.

**Comment by funkydude** [comment]
Why would I do that?

**Comment by funkydude** [comment]
"more accessible" lmao.

It's available from 3 websites: Curse, Wago, and WoWI. You can even get it from Curse via ANY SVN client of choice without interacting with their website or ads at all.

Just be honest, you want it available on GitHub so that you can have someone else's labor for free, whilst having GitHub's CDN bear the cost of providing it to you for free.

Looking at your GitHub page states "I like free software" and you sponsor nobody, typical.
